name: modul_4
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: "flutter"
  http: ^0.13.6
  intl: ^0.18.1
  image_picker: ^1.0.4
  image_gallery_saver: ^2.0.3
  geolocator: ^10.0.0
  permission_handler: ^11.0.0
  path_provider: ^2.1.1
  path: ^1.9.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
